// <auto-generated />
using System;
using ACEXAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACEXAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ACEXAPI.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CostoReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmpTransporteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolletoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PresupuestoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EmpTransporteId");

                    b.HasIndex("LocalizacionId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("ACEXAPI.Models.ActividadLocalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocalizacionId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacionId");

                    b.HasIndex("ActividadId", "LocalizacionId")
                        .IsUnique();

                    b.ToTable("ActividadLocalizaciones");
                });

            modelBuilder.Entity("ACEXAPI.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FacturaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PresupuestoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("ACEXAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nivel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nivel = "ESO",
                            Nombre = "1� ESO"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nivel = "ESO",
                            Nombre = "2� ESO"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nivel = "BACH",
                            Nombre = "1� Bach"
                        });
                });

            modelBuilder.Entity("ACEXAPI.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Departamento de Inform�tica",
                            Nombre = "Inform�tica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Departamento de Matem�ticas",
                            Nombre = "Matem�ticas"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Departamento de Lengua y Literatura",
                            Nombre = "Lengua"
                        });
                });

            modelBuilder.Entity("ACEXAPI.Models.EmpTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EmpTransportes");
                });

            modelBuilder.Entity("ACEXAPI.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlThumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ACEXAPI.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroAlumnos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ACEXAPI.Models.GrupoPartic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParticipantes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("GrupoId");

                    b.ToTable("GrupoPartics");
                });

            modelBuilder.Entity("ACEXAPI.Models.Localizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Localizaciones");
                });

            modelBuilder.Entity("ACEXAPI.Models.ProfParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProfesorUuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("ProfesorUuid");

                    b.ToTable("ProfParticipantes");
                });

            modelBuilder.Entity("ACEXAPI.Models.ProfResponsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCoordinador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProfesorUuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("ProfesorUuid");

                    b.ToTable("ProfResponsables");
                });

            modelBuilder.Entity("ACEXAPI.Models.Profesor", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Uuid");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("ACEXAPI.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ACEXAPI.Models.Actividad", b =>
                {
                    b.HasOne("ACEXAPI.Models.Departamento", "Departamento")
                        .WithMany("Actividades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ACEXAPI.Models.EmpTransporte", "EmpTransporte")
                        .WithMany("Actividades")
                        .HasForeignKey("EmpTransporteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ACEXAPI.Models.Localizacion", "Localizacion")
                        .WithMany("Actividades")
                        .HasForeignKey("LocalizacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departamento");

                    b.Navigation("EmpTransporte");

                    b.Navigation("Localizacion");
                });

            modelBuilder.Entity("ACEXAPI.Models.ActividadLocalizacion", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("ActividadLocalizaciones")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACEXAPI.Models.Localizacion", "Localizacion")
                        .WithMany("ActividadLocalizaciones")
                        .HasForeignKey("LocalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Localizacion");
                });

            modelBuilder.Entity("ACEXAPI.Models.Contrato", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("Contratos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("ACEXAPI.Models.Foto", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("Fotos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("ACEXAPI.Models.Grupo", b =>
                {
                    b.HasOne("ACEXAPI.Models.Curso", "Curso")
                        .WithMany("Grupos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("ACEXAPI.Models.GrupoPartic", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("GruposParticipantes")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACEXAPI.Models.Grupo", "Grupo")
                        .WithMany("ActividadesParticipantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ACEXAPI.Models.ProfParticipante", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("ProfesoresParticipantes")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACEXAPI.Models.Profesor", "Profesor")
                        .WithMany("ActividadesParticipante")
                        .HasForeignKey("ProfesorUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ACEXAPI.Models.ProfResponsable", b =>
                {
                    b.HasOne("ACEXAPI.Models.Actividad", "Actividad")
                        .WithMany("ProfesoresResponsables")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACEXAPI.Models.Profesor", "Profesor")
                        .WithMany("ActividadesResponsable")
                        .HasForeignKey("ProfesorUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ACEXAPI.Models.Profesor", b =>
                {
                    b.HasOne("ACEXAPI.Models.Departamento", "Departamento")
                        .WithMany("Profesores")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ACEXAPI.Models.Actividad", b =>
                {
                    b.Navigation("ActividadLocalizaciones");

                    b.Navigation("Contratos");

                    b.Navigation("Fotos");

                    b.Navigation("GruposParticipantes");

                    b.Navigation("ProfesoresParticipantes");

                    b.Navigation("ProfesoresResponsables");
                });

            modelBuilder.Entity("ACEXAPI.Models.Curso", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("ACEXAPI.Models.Departamento", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("ACEXAPI.Models.EmpTransporte", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("ACEXAPI.Models.Grupo", b =>
                {
                    b.Navigation("ActividadesParticipantes");
                });

            modelBuilder.Entity("ACEXAPI.Models.Localizacion", b =>
                {
                    b.Navigation("ActividadLocalizaciones");

                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("ACEXAPI.Models.Profesor", b =>
                {
                    b.Navigation("ActividadesParticipante");

                    b.Navigation("ActividadesResponsable");
                });
#pragma warning restore 612, 618
        }
    }
}
