// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDif9U1CH2ssVLTK0yDeh2-_C8SOlhTr7E',
    appId: '1:312191800375:web:763bafc4184da334099bb2',
    messagingSenderId: '312191800375',
    projectId: 'acexchat',
    authDomain: 'acexchat.firebaseapp.com',
    databaseURL: 'https://acexchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acexchat.firebasestorage.app',
    measurementId: 'G-B2VED5543T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX1sH9LkJk0F_FAmgiGneA8jSFuyXnHaY',
    appId: '1:312191800375:android:01a0a898e1616af5099bb2',
    messagingSenderId: '312191800375',
    projectId: 'acexchat',
    databaseURL: 'https://acexchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acexchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWIJ1NyqeOOYTegQHSFZfY9Cu2GplL-Ho',
    appId: '1:312191800375:ios:07c84e5a9605b9e1099bb2',
    messagingSenderId: '312191800375',
    projectId: 'acexchat',
    databaseURL: 'https://acexchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acexchat.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSanti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWIJ1NyqeOOYTegQHSFZfY9Cu2GplL-Ho',
    appId: '1:312191800375:ios:07c84e5a9605b9e1099bb2',
    messagingSenderId: '312191800375',
    projectId: 'acexchat',
    databaseURL: 'https://acexchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acexchat.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSanti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDif9U1CH2ssVLTK0yDeh2-_C8SOlhTr7E',
    appId: '1:312191800375:web:2edcce375b87efba099bb2',
    messagingSenderId: '312191800375',
    projectId: 'acexchat',
    authDomain: 'acexchat.firebaseapp.com',
    databaseURL: 'https://acexchat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acexchat.firebasestorage.app',
    measurementId: 'G-2VMEXT4V14',
  );
}
